# Generated by Django 3.2.20 on 2023-07-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='is_alarmed',
            new_name='alarm_ready',
        ),
    ]
