# Generated by Django 3.2.20 on 2023-07-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_is_alarmed_system_alarm_ready'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='alarm_ready',
            new_name='is_alarmed',
        ),
    ]
