# Generated by Django 3.2.20 on 2023-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_rename_alarm_ready_system_is_alarmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='is_alarmed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='monitoring URL',
            field=models.URLField(default=None, null=True),
        ),
    ]
