# Generated by Django 3.2.20 on 2023-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20230716_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='is_monitoring',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
