# Generated by Django 3.2.20 on 2023-07-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20230716_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='deprecation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='production_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='deprecation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='is_alarmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='is_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='monitoring URL',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='production_ready',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('url', models.URLField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uuid', to='manager.system')),
            ],
        ),
    ]
