# Generated by Django 3.2.20 on 2023-07-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20230716_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.IntegerField(choices=[(0, 'COME ES'), (1, 'COME PT'), (2, 'GAS TOP'), (3, 'AGENTE_VENDEDOR')], default=None)),
                ('process', models.CharField(max_length=100)),
            ],
        ),
    ]
