# Generated by Django 3.2.20 on 2023-07-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_businessprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='business_process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_process', to='manager.businessprocess'),
            preserve_default=False,
        ),
    ]
