# Generated by Django 3.2.20 on 2023-07-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_interface_business_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='business_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.businessprocess'),
        ),
    ]
