# Generated by Django 3.2.20 on 2023-07-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20230717_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='technology',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
