# Generated by Django 3.2.20 on 2023-07-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_system_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprocess',
            old_name='process',
            new_name='name',
        ),
    ]
