# Generated by Django 3.2.20 on 2023-07-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_rename_process_businessprocess_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
