# Generated by Django 3.2.20 on 2023-07-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_system_is_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
