# Generated by Django 4.2.3 on 2023-07-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_interface_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='is_alarmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interface',
            name='is_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interface',
            name='monitoring URL',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
