# Generated by Django 4.2.3 on 2023-07-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_interface_is_alarmed_interface_is_monitoring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='endpoints',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
    ]
