# Generated by Django 3.2.20 on 2023-07-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_remove_system_responsible_system_business_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='business_owner',
        ),
        migrations.RemoveField(
            model_name='system',
            name='it_owner',
        ),
        migrations.AddField(
            model_name='system',
            name='app_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system',
            name='business_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='system',
            name='infrastructure_monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
