# Generated by Django 3.2.20 on 2023-07-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20230724_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='diagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='url_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
    ]
