# Generated by Django 3.2.20 on 2023-07-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20230725_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='businessprocess',
            name='diagram_url',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='url_endpoint',
        ),
    ]
