# Generated by Django 3.2.20 on 2023-07-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20230726_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='business_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.department'),
        ),
    ]
