# Generated by Django 3.2.20 on 2023-07-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_businessprocess_business_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='it_owner',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
