# Generated by Django 3.2.20 on 2023-07-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_department_it_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
