# Generated by Django 3.2.20 on 2023-07-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_system_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprocess',
            name='department',
        ),
    ]
