# Generated by Django 3.2.20 on 2023-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_remove_businessprocess_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprocess',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='it_owner',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
