# Generated by Django 3.2.20 on 2023-07-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_remove_interface_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.technology'),
        ),
    ]
