# Generated by Django 3.2.20 on 2023-07-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_auto_20230727_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.technology'),
        ),
    ]
