# Generated by Django 3.2.20 on 2023-07-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_alter_interface_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='monitoring URL',
        ),
        migrations.RemoveField(
            model_name='system',
            name='monitoring URL',
        ),
    ]
